### ISSUE TITLE
Creating a project plan: Gantt-Milestones (10.11.20)

### ISSUE THREAD

**Issue by johannesstroebele91** [Marketing-AI/Recommendation-Application#9]
https://prod.teamgantt.com/gantt/schedule/?ids=2402063#ids=2402063&user=&custom=&company=&hide_completed=false&date_filter=&color_filter=

- [x] create project plan with gantt
- [x] specify working packages
- [x] adapt them to GitHub milestones
